### ISSUE TITLE
Snapshot files are in wrong folder

### ISSUE THREAD

**Issue by coxito** [xBimTeam/XbimBCF#1]
Hi,

When adding snapshots to a topic, the snapshot file is not added to the topic folder in the bcfzip file that is created (it is instead in the root folder). I traced down the reason for this in the \Xbim.BCF\BCF.cs file, in the Serialize() method. For snapshots, the code should be something like this:

```
foreach (KeyValuePair<String, byte[]> img in t.Snapshots)
{
	string snapshotName = string.Format("{0}/{1}", t.Markup.Topic.Guid, img.Key);
	var png = archive.CreateEntry(snapshotName);
	using (var pngStream = png.Open())
	{
		using (var pngWriter = new BinaryWriter(pngStream))
		{
			pngWriter.Write(img.Value);
			pngWriter.Close();
		}
	}
}
```

**Comment by LloydPickering** [comment]
I guess this is one for Andy to have a look at...

**Comment by MartinSchorr** [comment]
Hi,

any progress on this issue as I experienced the same problem today?

**Comment by CBenghi** [comment]
Hello @Wigliff,

I can have a look at this, but a PR would also be welcome, we are not maintaining this as a core piece of the framework, at some point I've used https://github.com/CBenghi/BCFier for the windowsUI BFC plugin, which seemed to work well.

Can you help me understand in what context you are using this?
What type of app or service are you running? Web/WindowsUI?

Thanks,
Claudio

**Comment by MartinSchorr** [comment]
Hello @CBenghi,

thank you for your quick reply! I'm using Xbim.BCF in order to serialize and deserialize bcf files from viewpoints taken from ifc files. It's working all pretty well despite the fact that the snapshot, taken from the viewpoint, is not included in the serialized bcf file. My code is mainly based on this code snippet:
http://stackoverflow.com/questions/42230059/bcf-file-creation

I also use BCFier to check the created bcf file visually. I rename the new file to *.bcfzip and open it up in the viewer. There I can see all information (topic, comment etc.) but it's missing the snapshot file. Inside of the bcf archive file I can see that the snapshot file resides in the root folder like @coxito mentioned. It is not inside of the markup subfolder like I can the in other bcf files.

I will have a look at your repository you supplied. I'm using WindowsUI (I believe). What I did was downloading the nuget package Xbim.BCF inside of Visual Studio.

Thank you,
Martin

**Comment by MartinSchorr** [comment]
@CBenghi,

this is the test code I'm using to produce the bcf file:

```var projectName = "Demo Project";
var projectId = "0HE7wY7irAE9b6u8RhVcUT";

// Guids
var topicGuid = Guid.NewGuid();
var viewePointGuid = Guid.NewGuid();

// Version
var bcfVersion = new VersionXMLFile("2.0");
bcfVersion.DetailedVersion = "2.0";

// ifc files
var ifcFile = new BCFFile();
ifcFile.Date = DateTime.Now;
ifcFile.Filename = "Sample.ifc";
ifcFile.IfcProject = projectId;
ifcFile.IfcSpatialStructureElement = "3sYjbGNsP7hQb8RP1A$gnO";

var listOfIfcFiles = new List<BCFFile>();
listOfIfcFiles.Add(ifcFile);

// vector data
var vectorOrthogonalCamera = new Vector(-3897.3178219783867, 4953.5118845010638, 4652.3131318143178);
var vectorCameraDirection = new Vector(0.10761971705126207, -0.23598312887050546, -0.16010308988365193);
var vectorCameraUpVector = new Vector(0.066432518104131186, -0.14566990055820389, 0.25936468651246125);

// comment(s)
var bcfComment = new BCFComment(
	Guid.NewGuid(),
	Guid.NewGuid(),
	"open",
	DateTime.Now,
	"Test User",
	"This needs to be replaced completely!");

bcfComment.Topic = new AttrIDNode(topicGuid);
bcfComment.Viewpoint = new AttrIDNode(viewePointGuid);

var listOfBcfComments = new List<BCFComment>();
listOfBcfComments.Add(bcfComment);

// topic
var bcfTopic = new BCFTopic(topicGuid, "Sample Topic");
bcfTopic.Description = "Beschreibung des Topics";

// snapshot(s)
var listOfSnapshots = new List<KeyValuePair<string, byte[]>> {
	new KeyValuePair<string, byte[]>("snapshot.png", File.ReadAllBytes("snapshot.png"))};

// view point
var bcfViewPoint = new BCFViewpoint(viewePointGuid)
{
	Snapshot = "snapshotNew.png",
	Viewpoint = "testFilename.bcfv"
};

var listOfBcfViewPoints = new List<BCFViewpoint>();
listOfBcfViewPoints.Add(bcfViewPoint);

var bcf = new BCF
{
	Project = new ProjectXMLFile
	{
		Project = new BCFProject
		{
			Name = projectName,
			ProjectId = projectId,
		},
	},
	Version = bcfVersion,
	Topics = new List<Topic> {
		new Topic {
			Markup = new MarkupXMLFile {
				Header = new BCFHeader {
					Files = listOfIfcFiles,
				},
				Comments = listOfBcfComments,
				Topic = bcfTopic,
				Viewpoints = listOfBcfViewPoints,
			},
			Snapshots = listOfSnapshots,
			Visualization = new VisualizationXMLFile {
				Components = new List<BCFComponent>(),
				OrthogonalCamera = new BCFOrthogonalCamera(vectorOrthogonalCamera, vectorCameraDirection, vectorCameraUpVector, 1)
			},
		},
	},
};

using (var output = File.Create("sample.bcf"))
{
	var data = bcf.Serialize();
	data.CopyTo(output);
	output.Close();
};
```
Martin

**Comment by CBenghi** [comment]
Hello @Wigliff ,
I've simply replaced the code as per @coxito suggestion, can you have a look if this makes sense upgrading your nuget to 3.1.10-v0001 (it's in the develop branch), if all works I'll commit to master.
Claudio

**Comment by MartinSchorr** [comment]
Hello @CBenghi,

using the new version with the bug fix it's working now.

I thank you very much for your help!

Cheers,
Martin

**Comment by CBenghi** [comment]
Good, 
I've merged to master and published to nuget.org.
Because of a few changes the version number is now 4.0.0, but it's essentially the same dll only signed and with other changes to the metadata.

PS. If you want to send info about your application usage I'm always curious to see how the toolkit is used, 
If you haven't yet maybe you want to fill in the short survey at: 

https://docs.google.com/forms/d/e/1FAIpQLScA4pq9qSXZQ9cLlnvVprJClRl3-6P4rme-g9B789726OuANw/viewform

Best,
Claudio
